# Python 101

In [268]:
import pandas as pd
import numpy as np

In [286]:
# convert list to array
import numpy as np
mylist = [1, 2, 3]
myarray = np.asarray(mylist)
# or, use the following: 
myarray = np.asarray([1,2,3])
print(myarray)

myarray = np.array([1,2,3])
print(myarray)

[1 2 3]
[1 2 3]


In [285]:
names = np.array(['bob', 'alice', 'bob', 'b', 'c', 'd', 'e'])
data = np.random.randn(7,4)
print(names)
print(data)
print(names =='bob') #returns [1,0,1,0,0,0,0]
print(data[names == 'bob']) #boolean index. Returns row 0 and 2. 

print('-----------array condition selection / select items in an array by condition')
array = np.arange(5)
print(array[array<3])

array = np.arange(5)
condition = np.logical_or(x < 1, x > 3)
print(array[condition])

['bob' 'alice' 'bob' 'b' 'c' 'd' 'e']
[[ 0.89610508 -0.25244843 -0.18217853  0.31310449]
 [ 0.15663681 -0.63542445  1.21675537 -0.54162041]
 [ 0.06740546 -0.56219897 -0.12890413 -1.25619993]
 [-0.91699585  0.89938511 -0.29403487  0.161036  ]
 [ 1.52811936  1.43033056 -1.82041957  1.16599003]
 [ 1.15483104 -0.28447624 -0.1985252   0.16566777]
 [ 0.67980654 -0.71683996 -1.48501873  0.02304603]]
[ True False  True False False False False]
[[ 0.89610508 -0.25244843 -0.18217853  0.31310449]
 [ 0.06740546 -0.56219897 -0.12890413 -1.25619993]]
-----------array condition selection / select items in an array by condition
[0 1 2]
[0 4]


In [61]:
myarray =np.array([0,0,0,0,0,1,1,1,1,1,1,1,2,2,2,2,2])
print(myarray.shape)
colors = np.array(['r', 'g', 'b'])
color_mapped_to_myarray = colors[myarray]
print(color_mapped_to_myarray)

(17,)
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'b' 'b' 'b' 'b' 'b']


In [82]:
# convert array to df / convert multiple arrays to dataframe
arr1 =np.array([1,2])
arr2 =np.array([-1,-2])
df = pd.DataFrame({'col1': arr1, 'col2': arr2})
display(df)

# convert ndarray to df / convert ndarray to dataframe
arr = np.array([[1,-1], [2, -2]])
df = pd.DataFrame({'col1': arr[:,0], 'col2': arr[:,1]})
display(df)

col1  col2
0     1    -1
1     2    -2

col1  col2
0     1    -1
1     2    -2

In [7]:
# convert dataframe/convert df column to array
x = df.iloc[:,0].values # convert a single column (col #0) to array
myndarray = df.iloc[:, :] #convert the whole dataframe to ndarray. Header included. 
myarray = df.iloc[:,[0,1]].values #convert column 0 and 1 to ndarray. No header. 
x = df['col2'].as_matrix() #convert the 'col2' col to array
x = df['col2'].values

# convert dataframe to list / convert df column to list
x = df['col2'].tolist()  #convert the 'col2' col to list


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """


In [ ]:
# see an object's type
print(type(x))

In [136]:
# Get the max/min number's index in an array
arr = np.array([10, -10, 2, 34])
print(np.argmax(arr), np.argmin(arr))
# get all the values under a condition in an array
print(arr[arr>=2])

# If/else condition to replace values in an array
newarr = np.where(arr>=0, 1, 0)
print(newarr)

print('----------------------')

# dot product of arrays 
arr1 = np.array([1,2])
arr3 = np.array([[2,4,5], [1,2,4]])
print(arr1.dot(arr3))
print(arr1 @ arr3) # another way to write it

# sort an array
print(np.sort(arr))

print('----------------------')

# transpose an array
print(arr3.T)

3 1
[10  2 34]
[1 0 1 1]
----------------------
[ 4  8 13]
[ 4  8 13]
[-10   2  10  34]
None
----------------------
[[2 1]
 [4 2]
 [5 4]]


### Map Function


In [244]:
# map function
mylist =list(range(10))
newlist = list(map(lambda x: x**2, mylist))
print(mylist)
print(newlist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Dictionary

In [267]:
# dictionary
# to count the number of each letter in a string
string = 'aaedkeiolccwwqbbbboe'
letter_dict = {i: string.count(i) for i in string }
print(letter_dict)
keys = letter_dict.keys()
values = letter_dict.values()
print(keys)
print(values)

{'a': 2, 'e': 3, 'd': 1, 'k': 1, 'i': 1, 'o': 2, 'l': 1, 'c': 2, 'w': 2, 'q': 1, 'b': 4}
dict_keys(['a', 'e', 'd', 'k', 'i', 'o', 'l', 'c', 'w', 'q', 'b'])
dict_values([2, 3, 1, 1, 1, 2, 1, 2, 2, 1, 4])


### List and Array

In [206]:
# sort
# watch for difference. 
mylist = [10, -1, 5]
print(sorted(mylist)) #won't get mutated
print(mylist)
mylist.sort() #use this if you want it mutated
print(mylist) #remember: if you use print(mylist.sort()), you will get nothing


print('-------------below: array-----------')
myarray = np.array([10, -1, 5])
print(np.sort(myarray))

[-1, 5, 10]
[10, -1, 5]
[-1, 5, 10]
-------------below: array-----------
[-1  5 10]


In [247]:
# sort
mylist = [1,3,5,-2]
print(sorted(mylist, key = lambda x:x**2 )) #list sort by specific method
print(sorted(mylist, key = lambda x:x**2, reverse = True)) #list sort descending by specific method
list_of_tuples = [(x, y) for x in range(3) for y in range(x+1, 4)]
print(list_of_tuples)
print(sorted(list_of_tuples, key = lambda x: x[1])) #sort by y's value

myarray = np.array([10, -1, 5])
print(np.sort(myarray))
print(-np.sort(-myarray)) #arrahy sort descending 

[-2, 5, 3, 1]


In [255]:
# reverse
mylist = [1,3,5,-2]
# to reverse the list 
mylist.reverse() 
print(mylist)

print('------------below array---------')
# Reverse the array
myarray = np.array([10, -1, 5])
myarray = myarray[::-1]
print(myarray)

myndarray= np.array([[2,4,5], [1,2,4]])
myndarray = myndarray[::-1]
print(myndarray)

[-2, 5, 3, 1]
------------below array---------
[ 5 -1 10]
[[1 2 4]
 [2 4 5]]


In [169]:
# extend
# watch for difference. 
mylist = [10, -1, 5]
newlist = [2,3]
mylist.extend(newlist)
print(mylist)
# Below method is wrong
# mynewlist = mylist.extend(newlist)
# print(mynewlist)

arr = np.array([10, -10, 2, 34])
arr = np.append(arr, [[5,6]])
print(arr)
arr = np.append(arr, [7,8])
print(arr)

[10, -1, 5, 2, 3]
[ 10 -10   2  34   5   6]
[ 10 -10   2  34   5   6   7   8]


In [180]:
# enumerate:  
# No difference
mylist =['a', 'b', 'c']
print(list(enumerate(mylist))) #enumerate each item in the list and its position
print(list(enumerate(mylist, start = 10))) #you can manually make it start at a certain number
for index, value in enumerate(mylist): 
    print('List: index is: ', index, ', value is: ', value)
    
arr = np.array(['a', 'b', 'c'])
print(list(enumerate(arr, start = 10))) 
for index, value in enumerate(arr): 
    print('Array: index is: ', index, ', value is: ', value)

[(0, 'a'), (1, 'b'), (2, 'c')]
[(10, 'a'), (11, 'b'), (12, 'c')]
List: index is:  0 , value is:  a
List: index is:  1 , value is:  b
List: index is:  2 , value is:  c
[(10, 'a'), (11, 'b'), (12, 'c')]
Array: index is:  0 , value is:  a
Array: index is:  1 , value is:  b
Array: index is:  2 , value is:  c


In [222]:
# Unpack list of tuples
list_of_tuples = [(x, y, z) for x in range(3) for y in range(x, 3) for z in range(x+y, 3)]
print(list_of_tuples)

print('A breakdown of how the triple_list is formed')
for x in range(3): 
    print('x', x)
    for y in range(x,3): 
        print('y', y)
        for z in range(x+y, 3): 
            print('z', z)

unpacked_list = [x for tup in list_of_tuples for x in tup]
print('Unpack list of tuples: ',unpacked_list)

# array: you can NOT put tuples in an array

[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 1), (0, 1, 2), (0, 2, 2), (1, 1, 2)]
A breakdown of how the triple_list is formed
x 0
y 0
z 0
z 1
z 2
y 1
z 1
z 2
y 2
z 2
x 1
y 1
z 2
y 2
x 2
y 2
Unpack list of tuples:  [0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 1, 0, 1, 2, 0, 2, 2, 1, 1, 2]
